### ISSUE TITLE
【第三周ID格式：USUMPM2】USUM OU 尝鲜期比赛

### ISSUE THREAD

**Issue by kirliavc** [kirliavc/blog#2]
### PS国服网址 http://china.psim.us/ 
**PS国服交流群：451507969
PS国服比赛群：106091896**
国服已经举办了一系列比赛，产生了多位获得专属头像的冠军选手。USUM来临之际，国服在此举办USUM OU 大赛，给大家提供训练、尝鲜的机会。

------

### 奖励【由EB老板赞助】
根据参加比赛的总人数，奖励如下表所示：

人数 | 第一名 | 第二名 | 第三名
---- | ------------- | ------------ | ------------
多于100人 | 国服头像+RMB 158 | 国服头像+RMB 78 | 国服头像+RMB 48
64~100人 | 国服头像+RMB 98 | 国服头像+RMB 48 | RMB 28
少于64人 | 国服头像+RMB 68 | 国服头像+RMB 38 | -

### 规则

1 **该系列赛事为USUM OU比赛，共分为两个部分：
　　A. 参加定时比赛 
　　B. 天梯刷分赛
比赛将持续三周的时间，并以周为单位。** 

2 **参加定时比赛**  每周的周末晚上都会有正式的USUM OU的单淘汰比赛，具体时间如下：

Week | 时间1 | 时间2 | 时间3 
---- | ------------- | ------------ | ------------
第一周 | 11.24周五晚9点30分 | 11.25周六晚9点30分 | 11.26周日晚8点 
第二周 | 12.1周五晚9点30分 | 12.2周六晚9点30分 | 12.3周日晚8点
第三周 | 12.8周五晚9点30分 | 12.9周六晚9点30分 | 12.10周日晚8点

**每位选手根据获胜场次计算分数。每取得一场胜利积2分，取得单场冠军的选手额外加5分，亚军选手加3分**

**参加定时比赛，需要使用相同的ID！** 不同的ID积分不会累计。

3 **天梯刷分赛** 天梯刷分赛分为三个周期，每个周期时长一周，如下表：

Week | 周期（截至第二个日期当天北京时间晚11：59）
---- | ------------- 
第一周 | 11.21-11.26 【周二~周日】
第二周 | 11.27-12.3  【周一~周日】
第三周 | 12.4-12.10   【周一~周日】

每个周期从上表每行中第一个日期的凌晨0点开始 (北京时间)，截至每行第二个日期当天晚11：59 (北京时间)

每一轮的关键词会准时公布，请留意国服Lobby和国服交流群451507969 / 国服比赛群 106091896
### 加分规则
每个周期结束时，天梯参赛ID中的前8个**合法ID**将根据下表获得积分：

名次 | 加分
---- | -----
第一名 | 23
第二名| 18
第三名 | 14
第四名 | 12
第五名 | 10
第六名| 9
第七名 | 8
第八名 | 7

### ID 要求
1 参加每周的比赛时，要求你使用的天梯ID包含连续完整的USUM+该周对应的特殊关键词

### 每周的关键词会在对应的一周开始时在PS国服公告中发布

例如：如果第一周的关键词是"atp"（大小写无所谓），那么 Mewtwo927USUMatp 是第一周的合法参赛ID，但在第二周不合法

而 USUM_FSKatp 则**不是**第一周的合法参赛ID，因为USUM和atp没有连在一起

例如：在第二周时，假如关键词是“lol”，排名第8的Mewtwo927USUMatp不再是合法参赛ID，不获得积分；

此时，如果第九名的ID是LXZUSUMlol，那么这一ID的拥有者将会获得积分

4 三周比赛结束后，最后两大部分的积分相加，将是选手的总分

5 为了方便统计结果，**请加比赛群 106091896** 方便收到比赛开始的提醒，并确认使用的PSID你的QQ

但是注意，参加比赛不需要提前报名，**只需要准时到场点击Join按钮加入**。但如果你想要积分，务必在比赛被淘汰后告知举办方你的QQ

6 比赛进行过程中，USUM OU规则可能发生变动，比赛的规则将完全以官服最新规则为准。

**关于Decay**

国服的Gen7 OU分级会在每天自动对全部玩家的天梯分数进行Decay。Decay的计算公式是：
```
New_Elo=(Elo-1000)*0.99+1000
```
Decay不会对玩家的排名造成影响。
## 积分榜 【将在比赛进行过程中随时更新】
https://github.com/CTCC1/linksio/blob/master/Leaderboard.md

------
### 国服比赛历届冠军
![【图片1】](https://i.imgur.com/xK4EDaW.jpg)

获得G4OU冠军的土著 

![【图片2】](https://i.imgur.com/shxi9Ey.jpg)

获得G6OU冠军的漫漫夜色

![【图片3】](https://i.imgur.com/0127VwO.jpg)

获得3DS 6V6冠军的kahili

**Comment by CTCC1** [comment]
已经有星际玩家不仔细阅读规则，问了一些傻傻的问题，特此前排提示一下：

### 请仔细阅读**开赛时间**
### 上方目前显示的ATP\LOL等ID要求**仅仅是举例**

具体的ID关键词要求会公布在国服LOBBY和此帖子的显著位置，公布时间是刷分周期第一个日期的北京时间0点

**Comment by kirliavc** [comment]
### 2017.11.24周五比赛结果
选手ID | 周五比赛分数
-- | --
Leply | 2
fddsb | 6
jerket | 2
uifu | 13
USUMAhh popoling | 2
USUMAHH buyi | 4
USUMAHHWGAY | 2
quickbantoxapex | 2
AshbringerUSUMAHH | 9

决赛战报
https://replay.pokemonshowdown.com/china-gen7ou-34179

**Comment by kirliavc** [comment]
### 2017.11.25周六比赛结果
 Nº | Name | Ranking | W | F | SF | Tours Played | Battles won
----|------|---------|---|---|----|-------------|-------------
1 | USUMAHH = DYWY | 15 | 1 | 0 | 0 | 1 | 5
2 | flowerkissusumahh | 9 | 0 | 1 | 0 | 1 | 3
3 | xy01 | 6 | 0 | 0 | 1 | 1 | 3
4 | xcellerate | 4 | 0 | 0 | 1 | 1 | 2
5 | lzaaaaa | 4 | 0 | 0 | 0 | 1 | 2
6 | Lancelot usumahh | 4 | 0 | 0 | 0 | 1 | 2
7 | woyaodaou | 2 | 0 | 0 | 0 | 1 | 1
8 | ss is damn long | 2 | 0 | 0 | 0 | 1 | 1
9 | sbaaa | 2 | 0 | 0 | 0 | 1 | 1
10 | quickbantoxapex | 2 | 0 | 0 | 0 | 1 | 1
11 | xxld6 | 2 | 0 | 0 | 0 | 1 | 1
12 | USUMahh FadedV | 2 | 0 | 0 | 0 | 1 | 1
13 | M•Diana | 0 | 0 | 0 | 0 | 1 | 0
14 | USUMAhh popoling | 0 | 0 | 0 | 0 | 1 | 0
15 | mexian.lapio | 0 | 0 | 0 | 0 | 1 | 0
16 | Guest 643 | 0 | 0 | 0 | 0 | 1 | 0
17 | usumahh666 | 0 | 0 | 0 | 0 | 1 | 0
18 | usumahhh | 0 | 0 | 0 | 0 | 1 | 0
19 | jerket | 0 | 0 | 0 | 0 | 1 | 0
20 | AVduiqienbn | 0 | 0 | 0 | 0 | 1 | 0
21 | usumagaoxiao | 0 | 0 | 0 | 0 | 1 | 0
22 | chb654200174 | 0 | 0 | 0 | 0 | 1 | 0
23 | fddsb | 0 | 0 | 0 | 0 | 1 | 0
24 | bkshtjj | 0 | 0 | 0 | 0 | 1 | 0

**Comment by kirliavc** [comment]
2017.11.26周日比赛结果 

Nº | Name | Ranking | W | F | SF | Tours Played | Battles won
----|------|---------|---|---|----|-------------|-------------
1 | usumahhDSB | 15 | 1 | 0 | 0 | 1 | 5
2 | USUMAhh popoling | 9 | 0 | 1 | 0 | 1 | 3
3 | LYNG USUMAHH | 6 | 0 | 0 | 1 | 1 | 3
4 | EroyalBoy | 4 | 0 | 0 | 1 | 1 | 2
5 | usumahh666 | 4 | 0 | 0 | 0 | 1 | 2
6 | gaojiguai | 4 | 0 | 0 | 0 | 1 | 2
7 | usumahhh | 2 | 0 | 0 | 0 | 1 | 1
8 | Paipai Otosaka | 2 | 0 | 0 | 0 | 1 | 1
9 | CelebiloveJirachi | 2 | 0 | 0 | 0 | 1 | 1
10 | Lancelot usumahh | 2 | 0 | 0 | 0 | 1 | 1
11 | Xcellerate | 2 | 0 | 0 | 0 | 1 | 1
12 | chb654200174 | 2 | 0 | 0 | 0 | 1 | 1
13 | sicuness | 0 | 0 | 0 | 0 | 1 | 0
14 | USUMAHH buyi | 0 | 0 | 0 | 0 | 1 | 0
15 | xujing691691 | 0 | 0 | 0 | 0 | 1 | 0
16 | Chaos23333 | 0 | 0 | 0 | 0 | 1 | 0
17 | usumahhtini | 0 | 0 | 0 | 0 | 1 | 0
18 | quickbantoxapex | 0 | 0 | 0 | 0 | 1 | 0
19 | Xxld6 | 0 | 0 | 0 | 0 | 1 | 0
20 | Alice USUMAHH | 0 | 0 | 0 | 0 | 1 | 0
21 | USUMahh FadedV | 0 | 0 | 0 | 0 | 1 | 0
22 | xy01 | 0 | 0 | 0 | 0 | 1 | 0
23 | usumahhUnown | 0 | 0 | 0 | 0 | 1 | 0
24 | woyaodaou | 0 | 0 | 0 | 0 | 1 | 0

**Comment by kirliavc** [comment]
第一周定时比赛分数统计

ID | Week1 tour score
-- | --
USUMAHH   = DYWY | 15
usumahhDSB = fddsb | 15
uifu | 13
AshbringerUSUMAHH | 9
flowerkissusumahh | 9
USUMAhh popoling | 9
fddsb | 6
LYNG USUMAHH | 6
xy01 | 6
EroyalBoy | 4
gaojiguai | 4
Lancelot usumahh | 4
lzaaaaa | 4
USUMAHH buyi | 4
usumahh666 | 4
xcellerate | 4
CelebiloveJirachi | 2
chb654200174 | 2
jerket | 2
Leply | 2
Paipai Otosaka | 2
quickbantoxapex | 2
sbaaa | 2
ss is damn long | 2
USUMahh FadedV | 2
usumahhh | 2
USUMAHHWGAY | 2
woyaodaou | 2
xxld6 | 2

**Comment by kirliavc** [comment]
第一周刷分赛结果

Rank | Elo | ID | Score
-- | -- | -- | --
1 | 1421.884 | usumahhhooh | 23
2 | 1382.274 | uuuusumahh | 18
3 | 1342.948 | usumahhDSB | 14
4 | 1336.055 | usumahhh | 12
5 | 1331.981 | jerketUSUMAHH | 10
6 | 1328.57 | Gawaineusumahh | 9
7 | 1306.948 | usumahhUnown | 8
8 | 1297.454 | USUMAHH buyi | 7

**Comment by kirliavc** [comment]
第一周总分

ID | Week1 tour | Week 1 ladder | Week1总分
-- | -- | -- | --
usumahhDSB = fddsb | 15 | 14 | 29
uifu | 13 | 12 | 25
usumahhhooh |   | 23 | 23
Aeca | 2 | 18 | 20
USUMAHH = DYWY | 15 |   | 15
Lancelot usumahh | 4 | 9 | 13
jerket | 2 | 10 | 12
USUMAHH buyi | 4 | 7 | 11
AshbringerUSUMAHH | 9 |   | 9
flowerkissusumahh | 9 |   | 9
USUMAhh popoling | 9 |   | 9
usumahhUnown |   | 8 | 8
LYNG USUMAHH | 6 |   | 6
xy01 | 6 |   | 6
EroyalBoy | 4 |   | 4
gaojiguai | 4 |   | 4
lzaaaaa | 4 |   | 4
usumahh666 | 4 |   | 4
xcellerate | 4 |   | 4
CelebiloveJirachi | 2 |   | 2
chb654200174 | 2 |   | 2
Leply | 2 |   | 2
Paipai Otosaka | 2 |   | 2
sbaaa | 2 |   | 2
ss is damn long | 2 |   | 2
USUMahh FadedV | 2 |   | 2
usumahhh | 2 |   | 2
USUMAHHWGAY | 2 |   | 2
woyaodaou | 2 |   | 2
xxld6 | 2 |   | 2

**Comment by kirliavc** [comment]
### 12.1周五比赛结果

 Nº | Name | Ranking | W | F | SF | Tours Played | Battles won
----|------|---------|---|---|----|-------------|-------------
1 | USUMYiu popoling | 13 | 1 | 0 | 0 | 1 | 4
2 | Giovanni Strike | 11 | 0 | 1 | 0 | 1 | 4
3 | asdfpaidf | 6 | 0 | 0 | 1 | 1 | 3
4 | xujing691691 | 4 | 0 | 0 | 1 | 1 | 2
5 | LzUSUMyiu | 4 | 0 | 0 | 0 | 1 | 2
6 | usumagaoxiao | 4 | 0 | 0 | 0 | 1 | 2
7 | usumyiu buyi | 2 | 0 | 0 | 0 | 1 | 1
8 | USUMyiuhooh | 2 | 0 | 0 | 0 | 1 | 1
9 | chb654200174 | 2 | 0 | 0 | 0 | 1 | 1
10 | Z-Ton | 2 | 0 | 0 | 0 | 1 | 1
11 | fyfyk2 | 2 | 0 | 0 | 0 | 1 | 1

**Comment by kirliavc** [comment]
12.2周六比赛结果

1 | LzUSUMyiu | 13
-- | -- | --
2 | uifu | 9
3 | xujing691691 | 4
4 | yaohui sama | 2
5 | abcdefog | 2
6 | Pusheen Birdway | 2

**Comment by kirliavc** [comment]
12.3周日比赛

 Nº | Name | Ranking | W | F | SF | Tours Played | Battles won
----|------|---------|---|---|----|-------------|-------------
1 | quickbantoxapex | 11 | 1 | 0 | 0 | 1 | 3
2 | YAOHUI SAMA | 7 | 0 | 1 | 0 | 1 | 2
3 | LzUSUMyiu | 4 | 0 | 0 | 1 | 1 | 2
4 | usumyiu buyi | 2 | 0 | 0 | 1 | 1 | 1
5 | uifu | 2 | 0 | 0 | 0 | 1 | 1

**Comment by kirliavc** [comment]
第二周定时比赛结果

Rank | ID | Score
-- | -- | --
1 | USUMYiu   popoling | 13
2 | LzUSUMyiu | 13
3 | quickbantoxapex | 11
4 | Giovanni Strike | 11
5 | uifu | 9
6 | YAOHUI SAMA | 7
7 | asdfpaidf | 6
8 | xujing691691 | 4
9 | usumagaoxiao | 4
10 | LzUSUMyiu | 4
11 | Z-Ton | 2
12 | USUMyiuhooh | 2
13 | usumyiu buyi | 2
14 | Pusheen Birdway | 2
15 | fyfyk2 | 2
16 | chb654200174 | 2
17 | abcdefog | 2

**Comment by kirliavc** [comment]
第二周刷分赛结果



Rank | ID | ELO | Score
-- | -- | -- | --
1 | usumyius | 1393.52 | 23
2 | Lancelot usumyiu | 1391.474 | 18
3 | yanzuUSUMYIUYIUYIU | 1339.732 | 14
4 | usumyiuu | 1337.621 | 12
5 | USUMyiuhooh | 1333.66 | 10
6 | USUMYIU | 1307.334 | 9
7 | AnyaUSUMYIU | 1303.685 | 8
8 | LzUSUMyiu | 1291.782 | 7

**Comment by kirliavc** [comment]
| ID | Week1总分 | Week2 tour | Week2 ladder | Week1+Week2
-- | -- | -- | -- | -- | --
1 | Aeca | 20 | 11 | 23 | 54
2 | usumahhDSB = fddsb | 29 | 7 | 14 | 50
3 | uifu | 25 | 9 | 12 | 46
4 | usumahhhooh | 23 | 2 | 10 | 35
5 | Lancelot usumahh | 13 | 2 | 18 | 33
6 | USUMAHH = DYWY | 15 | 2 | 9 | 26
7 | lzaaaaa | 4 | 13 | 7 | 24
8 | USUMAhh popoling | 9 | 13 |   | 22
9 | usumahhUnown | 8 | 11 |   | 19
10 | USUMAHH buyi | 11 | 2 |   | 13
11 | jerket | 12 |   |   | 12
12 | AshbringerUSUMAHH | 9 |   |   | 9
13 | flowerkissusumahh | 9 |   |   | 9
14 | AnyaUSUMYIU |   |   | 8 | 8
15 | LYNG USUMAHH | 6 |   |   | 6
16 | xy01 | 6 |   |   | 6
17 | asdfpaidf |   | 6 |   | 6
18 | EroyalBoy | 4 |   |   | 4
19 | gaojiguai | 4 |   |   | 4
20 | usumahh666 | 4 |   |   | 4
21 | xcellerate | 4 |   |   | 4
22 | chb654200174 | 2 | 2 |   | 4
23 | xujing691691 |   | 4 |   | 4
24 | usumagaoxiao |   | 4 |   | 4
25 | CelebiloveJirachi | 2 |   |   | 2
26 | Leply | 2 |   |   | 2
27 | Paipai Otosaka | 2 |   |   | 2
28 | sbaaa | 2 |   |   | 2
29 | ss is damn long | 2 |   |   | 2
30 | USUMahh FadedV | 2 |   |   | 2
31 | usumahhh | 2 |   |   | 2
32 | USUMAHHWGAY | 2 |   |   | 2
33 | woyaodaou | 2 |   |   | 2
34 | xxld6 | 2 |   |   | 2
35 | Z-Ton |   | 2 |   | 2
36 | abcdefog |   | 2 |   | 2

**Comment by kirliavc** [comment]
12.8 周五比赛
 
Nº | Name | Ranking | W | F | SF | Tours Played | Battles won
----|------|---------|---|---|----|-------------|-------------
1 | Aplysia | 11 | 1 | 0 | 0 | 1 | 3
2 | Chaos23333 | 7 | 0 | 1 | 0 | 1 | 2
3 | USUMPM2 = DYWY | 4 | 0 | 0 | 1 | 1 | 2
4 | FuckoffDeathStall | 2 | 0 | 0 | 1 | 1 | 1
5 | wlsdx6 | 2 | 0 | 0 | 0 | 1 | 1
6 | USUMPM2ez | 2 | 0 | 0 | 0 | 1 | 1

**Comment by kirliavc** [comment]
12.9 周六比赛 

Nº | Name | Ranking | W | F | SF | Tours Played | Battles won
----|------|---------|---|---|----|-------------|-------------
1 | popoling | 13 | 1 | 0 | 0 | 1 | 4
2 | dr.dmaria | 9 | 0 | 1 | 0 | 1 | 3
3 | f!vk sEy | 4 | 0 | 0 | 1 | 1 | 2
4 | uusumpm2 = uifu | 2 | 0 | 0 | 1 | 1 | 1
5 | Gayhua | 2 | 0 | 0 | 0 | 1 | 1
6 | USUMPM2 | 2 | 0 | 0 | 0 | 1 | 1
7 | fyfyk24 | 2 | 0 | 0 | 0 | 1 | 1

**Comment by kirliavc** [comment]
12.10 周日比赛

 Nº | Name | Ranking | W | F | SF | Tours Played | Battles won
----|------|---------|---|---|----|-------------|-------------
1 | LzUSUMPM2 | 11 | 1 | 0 | 0 | 1 | 3
2 | uuusumpm2 | 9 | 0 | 1 | 0 | 1 | 3
3 | xcellerate | 2 | 0 | 0 | 1 | 1 | 1
4 | AnyaUSUMPM2 | 2 | 0 | 0 | 1 | 1 | 1

**Comment by kirliavc** [comment]
第三周Tour总分

Rank | ID | score
-- | -- | --
1 | popoling | 13
2 | Aplysia | 11
3 | LzUSUMPM2 | 11
4 | uuusumpm2 | 9
5 | dr.dmaria | 9
6 | Chaos23333 | 7
7 | USUMPM2 = DYWY | 4
8 | f!vk sEy | 4
9 | xcellerate | 2
10 | wlsdx6 | 2
11 | USUMPM2ez | 2
12 | Gayhua | 2
13 | fyfyk24 | 2
14 | FuckoffDeathStall | 2
15 | AnyaUSUMPM2 | 2

**Comment by kirliavc** [comment]
第三周Ladder分数


Rank | Elo | ID | W | L | score
-- | -- | -- | -- | -- | --
1 | 1405.032 | usumpm2u | 32 | 6 | 23
2 | 1355.988 | USUMPM2EZ | 28 | 12 | 18
3 | 1340.235 | lol at usumpm2 | 16 | 6 | 14
4 | 1306.418 | USUMPM2 | 11 | 0 | 12
5 | 1292.533 | uusumpm2u | 25 | 17 | 10
6 | 1283.804 | uusumpm2 | 34 | 16 | 9
7 | 1269.49 | LzUSUMPM2 | 13 | 6 | 8
8 | 1232.355 | AnyaUSUMPM2 | 19 | 12 | 7

**Comment by kirliavc** [comment]
比赛总分前8

Rank | ID | Week1+Week2 | Week3 tour | Week3 ladder | Total
-- | -- | -- | -- | -- | --
1 | Aeca | 54 | 4 | 14 | 72
2 | usumahhDSB = fddsb | 50 | 2 | 18 | 70
3 | uifu | 46 | 9 | 10 | 65
4 | Lancelot usumahh | 33 | 2 | 23 | 58
5 | lzaaaaa | 24 | 11 | 8 | 43
6 | USUMAHH = DYWY | 26 | 4 | 12 | 42
7 | usumahhhooh | 35 |   |   | 35
8 | USUMAhh popoling | 22 | 13 |   | 35
